// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $api_slides_id_ from './routes/api/slides/[id].ts'
import * as $api_slides_index from './routes/api/slides/index.ts'
import * as $index from './routes/index.tsx'
import * as $slide from './routes/slide.tsx'
import * as $Slide from './islands/Slide.tsx'
import { type Manifest } from '$fresh/server.ts'

const manifest = {
	routes: {
		'./routes/_404.tsx': $_404,
		'./routes/_app.tsx': $_app,
		'./routes/api/slides/[id].ts': $api_slides_id_,
		'./routes/api/slides/index.ts': $api_slides_index,
		'./routes/index.tsx': $index,
		'./routes/slide.tsx': $slide,
	},
	islands: {
		'./islands/Slide.tsx': $Slide,
	},
	baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
